fun main() {
    println("Manipulacion de listas - Consultas Medicas")
    println("Crear una lista")
    val vacia = mutableListOf<String>()
    println(vacia)
    val turnos = mutableListOf(1, 2, 3, 4, 5)
    println(turnos)
    val pacientes = mutableListOf("Carlos", "Maria", "Juan")
    println(pacientes)
    val datosConsulta = mutableListOf<Any>(1, "Fiebre", 38.5, true)
    println(datosConsulta)

    println("Acceso a los elementos de una lista")
    println(pacientes[1])
    println(pacientes[pacientes.size - 1])
    println(pacientes.subList(1, 3))
    println(pacientes.reversed())

    println("Crud de listas - Medicamentos")
    val medicamentos = mutableListOf("Paracetamol", "Ibuprofeno", "Amoxicilina")
    medicamentos.add(2, "Omeprazol")
    medicamentos.add("Metformina")
    println(medicamentos)
    medicamentos.addAll(listOf("Aspirina", "Diazepam"))
    medicamentos[0] = "Acetaminofen"
    println(medicamentos)
    medicamentos.remove("Ibuprofeno")
    println(medicamentos)
    val eliminado = medicamentos.removeAt(2)
    println(eliminado)
    println(medicamentos)
    medicamentos.removeAt(0)
    println(medicamentos)
}
